config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :widgets

  root 'welcome#index'

=======

  devise_for :admins
  root 'pages#home'

  devise_for  :users,
              :path => "",
              :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" },
              :path_names => {:sign_in => "login",
              :sign_out => "logout",
              :edit => "profile"}

  resources :users, only: [:show] do
    resources :galleries
    resources :pictures
  end

  resources :products
  resources :product_photos

  patch "/users/:user_id" => "users#update"

  get "/about_us" => "pages#about_us"

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get 'search', to: 'users#show'

  resources :products do
    resources :transactions, only: [:create]
  end

>>>>>>> 0478bb66c5aeed21944167d5aa1235cba3cbc3ed
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :fullname, presence: true, length: {maximum: 50}

  has_many :products

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?",
      user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?)
      OR (conversations.sender_id = ? AND conversations.recipient_id = ?)",
      sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

  belongs_to :user
  has_many :pictures, :dependent => :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
    created_at.strftime("%r")
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :gallery
  belongs_to :user

  has_attached_file :image,
    :path => ":rails_root/public/images/:id/:filename",
    :url  => "/images/:id/:filename"

  do_not_validate_attachment_file_type :image

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  # validates_presence_of :product_type
  # validates_presence_of :category
  # validates_presence_of :size
  # validates_presence_of :product_name, length: {maximum: 50}
  # validates_presence_of :description, length: {maximum: 500}
  # validates_presence_of :stock
  # validates_presence_of :code_id
  # validates_presence_of :price


  has_many :product_photos
  has_many :transactions

end

app/models/product_photo.rb
class ProductPhoto < ActiveRecord::Base
  belongs_to :product

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    devise :omniauthable, :omniauth_providers => [:facebook]
    validates :fullname, presence: true, length: {maximum: 50}
    validates :code, uniqueness: true

    has_many :products
    has_many :galleries
    has_many :photos
    has_many :transactions

    #devise :registerable, :confirmable
    before_create :confirmation_token

    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50#", profile: '200x200>' }, default_url: nil
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.fullname = auth.info.name   # assuming the user model has a name
        user.avatar = auth.info.image # assuming the user model has an image
        end
    end

    def generate_code
        self.code = (("A".."Z").to_a.sample(1) + (0..9).to_a.sample(4)).join
    end


end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new( user_params )
    @user.code = User.code_generator
    if @user.save
        redirect_to @user
    else
        render :new
    end
  end

  def show
    @user = User.find_by(code: params[:code])
    if @user.nil?
      redirect_to "/"
    else
      @user.errors.full_messages
    end

  end

  def update
    @user = User.find(params[:user_id])
    @user.update(premium_params)
    redirect_to @user
  end

  private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:avatar)
  end


  def premium_params
    params.require(:user).permit(:code)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
<<<<<<< HEAD
=======
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    if user.image
      user.image
    else
      "http://gravatar.com/avatar/#{gravatar_id}.jpg?s=150"
    end
  end
>>>>>>> 0478bb66c5aeed21944167d5aa1235cba3cbc3ed
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/admin/_home.html.erb
LIST OF PRODUCTS

app/views/admin/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Trail</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Store</a></li>
        <li><%= link_to "Products", products_path %></li>
        <li>
          <%= link_to new_product_path do %>
            <i class="fa fa-home" aria-hidden="true"></i> Add New Product
          <% end %>
        </li>
        <li><a href="#">Orders</a></li>
        <li><a href="#">Users</a></li>
        <li>
          <a href="#">Inbox</a>
            <i class="fa fa-envelope-o" aria-hidden="true"></i>
        </li>

        <li><%= link_to "Log Out", destroy_admin_session_path, method: :delete %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/_devisenotify.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error['<%= msg %>']
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Menu -->
<nav class="menu" id="theMenu">
  <div class="menu-wrap">
    <h1 class="logo"><a href="/">TRAIL</a></h1>
    <i class="icon-remove menu-close"></i>
    <!-- <a href="#home">FIND</a> -->
    <% if(!user_signed_in?) %>
    <%= link_to "Log In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
    <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
    <% else %>
    <a href="/users/<%=current_user.id%>"><%="#{current_user.fullname}"%></a>
    <%= link_to "Edit Profile", edit_user_registration_path %>
    <%= link_to "Messages", conversations_path %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    <% end %>

    <hr class="nav_bar">
    <a href="/products">Store</a>
    <a href="/about_us">About Us</a>

    <a href="#contact">Contact</a>
    <a href="#contact"></a>
    <a href="#"><i class="icon-facebook"></i></a>
    <a href="#"><i class="icon-twitter"></i></a>
    <a href="#"><i class="icon-dribbble"></i></a>
    <a href="#"><i class="icon-envelope"></i></a>
    <a href="#"><i class="fa fa-shopping-cart"></i></a>
  </div>

  <!-- Menu button -->
  <div id="menuToggle"><i class="icon-reorder"></i></div>
</nav>

app/views/shared/_notify.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>